### ISSUE TITLE
player.stop() remove <source>

### ISSUE THREAD

**Issue by dalibor-sojic** [colthreepv/angular-media-player#80]
Here is the code I have:
`<audio media-player="player" data-playlist="playlist">
    <source src="http://radio.stream.url.mp3" type="audio/mpeg">
    <source src="http://radio.stream.url.aac" type="audio/aac">
</audio>`

When I want to stop the playing, player.stop, remove all <source> elements, and not possible to continue with play later.

**Comment by dalibor-sojic** [comment]
Got it... player.play(0), will regenerate and it works!

**Comment by colthreepv** [comment]
well I am very happy this still works ... but keep in mind this lib is soo outdated and deprecated that I am not reccomending it's use anymore 👍
