### ISSUE TITLE
How to use this package into angular 7

### ISSUE THREAD

**Issue by NikitaPooja** [colthreepv/angular-media-player#82]
I don't understand how to use this code 

angular.module('myApp').controller('MyController', function ($scope) {

  // access properties
  console.log($scope.audio1.network);
  console.log($scope.audio1.ended);

  $scope.mySpecialPlayButton = function () {
    $scope.customText = 'I started angular-media-player with a custom defined action!';
    $scope.audio1.playPause();
  };
})

**Comment by colthreepv** [comment]
This is an old and deprecated project.

It's not suitable for anything past angular 1.x
